apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-api
  labels:
    app: protected-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protected-api
  template:
    metadata:
      labels:
        app: protected-api
    spec:
      containers:
        - name: protected-api
          image: zero-trust-protected-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: protected-api
spec:
  selector:
    app: protected-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
