apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-echo
  labels:
    app: backend-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-echo
  template:
    metadata:
      labels:
        app: backend-echo
    spec:
      containers:
        - name: echo
          image: zero-trust-echo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
