{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  labels:
    {{- include "zero-trust-mtls.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "zero-trust-mtls.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.env.POSTGRES_PASSWORD }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
{{- end }}
